{
    "data": {
        "UPIAmountLimitWarn": "UPI mode not support for amount exceed than Rs 99950.00",
        "chargeList": [],
        "isOnlinePaymentEnabled": true,
        "ScScholarHeads": [
            {
                "accountHeadId": null,
                "accountGroupId": null,
                "finFeesId": 55,
                "finFeesName": null,
                "feeHeadOrder": null,
                "feeType": null,
                "feeHeadShortName": null,
                "description": null
            },
            {
                "accountHeadId": null,
                "accountGroupId": null,
                "finFeesId": 56,
                "finFeesName": null,
                "feeHeadOrder": null,
                "feeType": null,
                "feeHeadShortName": null,
                "description": null
            }
        ],
        "studentDetails": {
            "studentId": 7621,
            "studentFullName": "PRITAM UTTAM SARKAR",
            "registrationNo": "GHRUA23011140629",
            "email": null,
            "academicYearId": 7,
            "degreeName": "BCA",
            "branchName": "BCA",
            "yearName": "II",
            "semesterName": "III",
            "academicBatchName": "2023-2026",
            "classSectionName": "BCA_C_NG",
            "rollNo": "BCA-NG-E-68",
            "academicSessionName": "Winter 2024",
            "studAcademicFeesDtlsList": null,
            "studReceivableDtlsList": null,
            "studentFeeTotalAmtDtls": null,
            "studReceivableTotalAmtDtls": null,
            "profilePhoto": "https://ghrua.cybervidya.net/api/admission/student/assets/7621",
            "installmentName": null,
            "installmentDueAmt": null,
            "installmentDueDate": null,
            "admissionCategory": "Management",
            "casteCategory": "OPEN",
            "feesCategoryName": "General",
            "lastUpdatedTime": null,
            "enrollmentType": "First Year",
            "currentAcademicYearName": "2024-25",
            "acadmeciOninePaymentStatus": false,
            "message": null,
            "degreeId": 39,
            "branchId": 295,
            "studyLocId": null,
            "studentGroupId": 2,
            "isOnlinePaymentEnabled": null,
            "feesHeadName": null,
            "amount": null,
            "scholarshipAmount": null,
            "totalAmount": null,
            "grandAmount": null,
            "applicableFeesDtls": null,
            "applicableIconFlag": false,
            "financialYearId": null,
            "finYearWiseFeesDecls": null,
            "financialYearName": null,
            "branchShortName": null,
            "academicYearName": null,
            "isOnlinePaymentTypeAll": null,
            "chargeList": null,
            "scScholarshipHeads": null,
            "scheduledPromNote": null,
            "outstandingAmount": null,
            "paymentStatus": null,
            "upiamountLimitWarn": null
        },
        "studentFeesPaymentDtls": [
            {
                "academicYearId": 6,
                "academicYearName": "2023-24",
                "installmentName": null,
                "installmentDueAmt": null,
                "installmentDueDate": null,
                "studAcademicFeesDtlsList": [
                    {
                        "id": null,
                        "feesHeadId": 4,
                        "feesHeadName": "Tuition fee",
                        "totalReceivablesAmt": 45500.0,
                        "totalCollectedAmt": 45500.0,
                        "outstandingAmt": 0.0,
                        "amount": 0.0,
                        "finalOutstandingAmt": null,
                        "feesDeclarationDtlsId": null,
                        "feesReceivableDtlsId": null,
                        "isFeesHeadAmtPaid": null,
                        "feesType": null,
                        "paymentStatus": "Paid",
                        "refundAmt": null,
                        "chargeAmt": null,
                        "chargesTowardsId": null,
                        "chargesTowardsName": null,
                        "isValidation": true,
                        "isAdvanceHead": false,
                        "headShortname": "Tuition fee",
                        "isDisable": false,
                        "isSettelSelect": false,
                        "isConcessionOnly": false,
                        "isFeeMandatory": null,
                        "mandatoryFeeFinalOutstandingAmt": null,
                        "fromAmount": null,
                        "toAmount": null,
                        "charge": null,
                        "feeHeadOrder": null,
                        "studentFinalOutanding": null,
                        "preStudentFinalOutanding": null
                    },
                    {
                        "id": null,
                        "feesHeadId": 44,
                        "feesHeadName": "Alumni Fund",
                        "totalReceivablesAmt": 1000.0,
                        "totalCollectedAmt": 1000.0,
                        "outstandingAmt": 0.0,
                        "amount": 0.0,
                        "finalOutstandingAmt": null,
                        "feesDeclarationDtlsId": null,
                        "feesReceivableDtlsId": null,
                        "isFeesHeadAmtPaid": null,
                        "feesType": null,
                        "paymentStatus": "Paid",
                        "refundAmt": null,
                        "chargeAmt": null,
                        "chargesTowardsId": null,
                        "chargesTowardsName": null,
                        "isValidation": true,
                        "isAdvanceHead": false,
                        "headShortname": "Alumni Fund",
                        "isDisable": false,
                        "isSettelSelect": false,
                        "isConcessionOnly": false,
                        "isFeeMandatory": null,
                        "mandatoryFeeFinalOutstandingAmt": null,
                        "fromAmount": null,
                        "toAmount": null,
                        "charge": null,
                        "feeHeadOrder": null,
                        "studentFinalOutanding": null,
                        "preStudentFinalOutanding": null
                    },
                    {
                        "id": null,
                        "feesHeadId": 1,
                        "feesHeadName": "Advance Fees",
                        "totalReceivablesAmt": 0.0,
                        "totalCollectedAmt": 0.0,
                        "outstandingAmt": 0.0,
                        "amount": 0.0,
                        "finalOutstandingAmt": null,
                        "feesDeclarationDtlsId": null,
                        "feesReceivableDtlsId": null,
                        "isFeesHeadAmtPaid": null,
                        "feesType": null,
                        "paymentStatus": "No Dues",
                        "refundAmt": null,
                        "chargeAmt": null,
                        "chargesTowardsId": null,
                        "chargesTowardsName": null,
                        "isValidation": true,
                        "isAdvanceHead": true,
                        "headShortname": "Advance Fees",
                        "isDisable": false,
                        "isSettelSelect": false,
                        "isConcessionOnly": false,
                        "isFeeMandatory": null,
                        "mandatoryFeeFinalOutstandingAmt": null,
                        "fromAmount": null,
                        "toAmount": null,
                        "charge": null,
                        "feeHeadOrder": null,
                        "studentFinalOutanding": null,
                        "preStudentFinalOutanding": null
                    }
                ],
                "studReceivableDtlsList": [
                    {
                        "id": null,
                        "feesHeadId": 48,
                        "feesHeadName": "End Semester Exam Fee",
                        "totalReceivablesAmt": 3200.0,
                        "totalCollectedAmt": 3200.0,
                        "outstandingAmt": 0.0,
                        "amount": 0.0,
                        "finalOutstandingAmt": null,
                        "feesDeclarationDtlsId": null,
                        "feesReceivableDtlsId": null,
                        "isFeesHeadAmtPaid": null,
                        "feesType": null,
                        "paymentStatus": "Paid",
                        "refundAmt": null,
                        "chargeAmt": null,
                        "chargesTowardsId": null,
                        "chargesTowardsName": null,
                        "isValidation": true,
                        "isAdvanceHead": false,
                        "headShortname": "End Semester Exam Fee",
                        "isDisable": false,
                        "isSettelSelect": false,
                        "isConcessionOnly": false,
                        "isFeeMandatory": null,
                        "mandatoryFeeFinalOutstandingAmt": null,
                        "fromAmount": null,
                        "toAmount": null,
                        "charge": null,
                        "feeHeadOrder": null,
                        "studentFinalOutanding": null,
                        "preStudentFinalOutanding": null
                    }
                ],
                "studentFeeTotalAmtDtls": {
                    "totalReceivableAmt": 46500.0,
                    "totalCollectedAmt": 46500.0,
                    "totalOutstandingAmt": 0.0,
                    "totalAmt": null,
                    "totalFinalOutstandingAmt": null,
                    "totalRefundAmt": 0.0,
                    "totalCharges": 0.0
                },
                "studReceivableTotalAmtDtls": {
                    "totalReceivableAmt": 3200.0,
                    "totalCollectedAmt": 3200.0,
                    "totalOutstandingAmt": 0.0,
                    "totalAmt": null,
                    "totalFinalOutstandingAmt": null,
                    "totalRefundAmt": 0.0,
                    "totalCharges": 0.0
                },
                "studentPaymentHistoryList": null,
                "scholarshipAmount": 0.0,
                "promotionStatus": null,
                "configYearName": "I",
                "isInstallmentDisable": true,
                "financialYearId": 3,
                "financialYearName": "2023-2024",
                "acadmeciOninePaymentStatus": false,
                "othersOnlineOaymentStatus": false,
                "lastUpdatedTime": 1733541139297,
                "message": null,
                "scheduledPromNote": null,
                "outstandingAmount": 0.0,
                "paymentStatus": "PAID"
            },
            {
                "academicYearId": 7,
                "academicYearName": "2024-25",
                "installmentName": null,
                "installmentDueAmt": null,
                "installmentDueDate": null,
                "studAcademicFeesDtlsList": [
                    {
                        "id": null,
                        "feesHeadId": 4,
                        "feesHeadName": "Tuition fee",
                        "totalReceivablesAmt": 45500.0,
                        "totalCollectedAmt": 45500.0,
                        "outstandingAmt": 0.0,
                        "amount": 0.0,
                        "finalOutstandingAmt": null,
                        "feesDeclarationDtlsId": null,
                        "feesReceivableDtlsId": null,
                        "isFeesHeadAmtPaid": null,
                        "feesType": null,
                        "paymentStatus": "Paid",
                        "refundAmt": null,
                        "chargeAmt": null,
                        "chargesTowardsId": null,
                        "chargesTowardsName": null,
                        "isValidation": true,
                        "isAdvanceHead": false,
                        "headShortname": "Tuition fee",
                        "isDisable": false,
                        "isSettelSelect": false,
                        "isConcessionOnly": false,
                        "isFeeMandatory": null,
                        "mandatoryFeeFinalOutstandingAmt": null,
                        "fromAmount": null,
                        "toAmount": null,
                        "charge": null,
                        "feeHeadOrder": null,
                        "studentFinalOutanding": null,
                        "preStudentFinalOutanding": null
                    },
                    {
                        "id": null,
                        "feesHeadId": 59,
                        "feesHeadName": "Examination Fees",
                        "totalReceivablesAmt": 3500.0,
                        "totalCollectedAmt": 3500.0,
                        "outstandingAmt": 0.0,
                        "amount": 0.0,
                        "finalOutstandingAmt": null,
                        "feesDeclarationDtlsId": null,
                        "feesReceivableDtlsId": null,
                        "isFeesHeadAmtPaid": null,
                        "feesType": null,
                        "paymentStatus": "Paid",
                        "refundAmt": null,
                        "chargeAmt": null,
                        "chargesTowardsId": null,
                        "chargesTowardsName": null,
                        "isValidation": true,
                        "isAdvanceHead": false,
                        "headShortname": "Examination Fees",
                        "isDisable": false,
                        "isSettelSelect": false,
                        "isConcessionOnly": false,
                        "isFeeMandatory": null,
                        "mandatoryFeeFinalOutstandingAmt": null,
                        "fromAmount": null,
                        "toAmount": null,
                        "charge": null,
                        "feeHeadOrder": null,
                        "studentFinalOutanding": null,
                        "preStudentFinalOutanding": null
                    },
                    {
                        "id": null,
                        "feesHeadId": 1,
                        "feesHeadName": "Advance Fees",
                        "totalReceivablesAmt": 0.0,
                        "totalCollectedAmt": 0.0,
                        "outstandingAmt": 0.0,
                        "amount": 0.0,
                        "finalOutstandingAmt": null,
                        "feesDeclarationDtlsId": null,
                        "feesReceivableDtlsId": null,
                        "isFeesHeadAmtPaid": null,
                        "feesType": null,
                        "paymentStatus": "No Dues",
                        "refundAmt": null,
                        "chargeAmt": null,
                        "chargesTowardsId": null,
                        "chargesTowardsName": null,
                        "isValidation": true,
                        "isAdvanceHead": true,
                        "headShortname": "Advance Fees",
                        "isDisable": false,
                        "isSettelSelect": false,
                        "isConcessionOnly": false,
                        "isFeeMandatory": null,
                        "mandatoryFeeFinalOutstandingAmt": null,
                        "fromAmount": null,
                        "toAmount": null,
                        "charge": null,
                        "feeHeadOrder": null,
                        "studentFinalOutanding": null,
                        "preStudentFinalOutanding": null
                    }
                ],
                "studReceivableDtlsList": [
                    {
                        "id": null,
                        "feesHeadId": 28,
                        "feesHeadName": "Late Fees Fine",
                        "totalReceivablesAmt": 4300.0,
                        "totalCollectedAmt": 4300.0,
                        "outstandingAmt": 0.0,
                        "amount": 0.0,
                        "finalOutstandingAmt": null,
                        "feesDeclarationDtlsId": null,
                        "feesReceivableDtlsId": null,
                        "isFeesHeadAmtPaid": null,
                        "feesType": null,
                        "paymentStatus": "Paid",
                        "refundAmt": null,
                        "chargeAmt": null,
                        "chargesTowardsId": null,
                        "chargesTowardsName": null,
                        "isValidation": true,
                        "isAdvanceHead": false,
                        "headShortname": "Late Fees Fine",
                        "isDisable": false,
                        "isSettelSelect": false,
                        "isConcessionOnly": false,
                        "isFeeMandatory": null,
                        "mandatoryFeeFinalOutstandingAmt": null,
                        "fromAmount": null,
                        "toAmount": null,
                        "charge": null,
                        "feeHeadOrder": null,
                        "studentFinalOutanding": null,
                        "preStudentFinalOutanding": null
                    },
                    {
                        "id": null,
                        "feesHeadId": 57,
                        "feesHeadName": "Prospectus Fees",
                        "totalReceivablesAmt": 150.0,
                        "totalCollectedAmt": 150.0,
                        "outstandingAmt": 0.0,
                        "amount": 0.0,
                        "finalOutstandingAmt": null,
                        "feesDeclarationDtlsId": null,
                        "feesReceivableDtlsId": null,
                        "isFeesHeadAmtPaid": null,
                        "feesType": null,
                        "paymentStatus": "Paid",
                        "refundAmt": null,
                        "chargeAmt": null,
                        "chargesTowardsId": null,
                        "chargesTowardsName": null,
                        "isValidation": true,
                        "isAdvanceHead": false,
                        "headShortname": "Prospectus Fees",
                        "isDisable": false,
                        "isSettelSelect": false,
                        "isConcessionOnly": false,
                        "isFeeMandatory": null,
                        "mandatoryFeeFinalOutstandingAmt": null,
                        "fromAmount": null,
                        "toAmount": null,
                        "charge": null,
                        "feeHeadOrder": null,
                        "studentFinalOutanding": null,
                        "preStudentFinalOutanding": null
                    }
                ],
                "studentFeeTotalAmtDtls": {
                    "totalReceivableAmt": 49000.0,
                    "totalCollectedAmt": 49000.0,
                    "totalOutstandingAmt": 0.0,
                    "totalAmt": null,
                    "totalFinalOutstandingAmt": null,
                    "totalRefundAmt": 0.0,
                    "totalCharges": 0.0
                },
                "studReceivableTotalAmtDtls": {
                    "totalReceivableAmt": 4450.0,
                    "totalCollectedAmt": 4450.0,
                    "totalOutstandingAmt": 0.0,
                    "totalAmt": null,
                    "totalFinalOutstandingAmt": null,
                    "totalRefundAmt": 0.0,
                    "totalCharges": 0.0
                },
                "studentPaymentHistoryList": null,
                "scholarshipAmount": 0.0,
                "promotionStatus": null,
                "configYearName": "II",
                "isInstallmentDisable": false,
                "financialYearId": 4,
                "financialYearName": "2024-2025",
                "acadmeciOninePaymentStatus": true,
                "othersOnlineOaymentStatus": false,
                "lastUpdatedTime": 1733541139297,
                "message": null,
                "scheduledPromNote": null,
                "outstandingAmount": 0.0,
                "paymentStatus": "PAID"
            }
        ],
        "isOnlinePaymentTypeAll": false
    },
    "timeStamp": "2025.02.03.20.19.38",
    "message": "Student fees payment history fetch successfully",
    "version": "BETA Version",
    "reload": false
}